### ISSUE TITLE
Error running example script scrape_and_parse_with_ai_job_page.py

### ISSUE THREAD

**Issue by damienkilgannon** [oxylabs/OxyParser#6]
```
(oxyparser) % python --version
Python 3.8.17
```

```
(oxyparser) % python scrape_and_parse_with_ai_job_page.py
Traceback (most recent call last):
  File "scrape_and_parse_with_ai_job_page.py", line 3, in <module>
    from oxyparser.oxyparser import OxyParser
  File "/.pyenv/versions/oxyparser/lib/python3.8/site-packages/oxyparser/oxyparser.py", line 7, in <module>
    from oxyparser.cache.base import BaseCache
  File "/.pyenv/versions/oxyparser/lib/python3.8/site-packages/oxyparser/cache/base.py", line 5, in <module>
    class BaseCache:
  File "/.pyenv/versions/oxyparser/lib/python3.8/site-packages/oxyparser/cache/base.py", line 9, in BaseCache
    async def get(self, domain: str) -> dict[str, list[str]]:
TypeError: 'type' object is not subscriptable
```

**Comment by oxytadasgedgaudas** [comment]
Hey! Thanks for opening the issue. 

We changed the minimum python version supported by the project to 3.10

anything lower than 3.10 is not supported at the moment..
